### ISSUE TITLE
imap fails since namespace "INBOX"

### ISSUE THREAD

**Issue by mtauz** [JojiiOfficial/Matrix-EmailBot#7]
I am getting the following Error:
`
[error] #12 couldnt get INBOX Client tried to access nonexiste
nt namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0
.000 secs).
`
I am testing the Matrix-EmailBot, Login on Matrix runs fine, also sending an eMail via the same account ist running fine, just imap bridging to Matrix fails.

**Comment by JojiiOfficial** [comment]
> I am getting the following Error:
> `[error] #12 couldnt get INBOX Client tried to access nonexiste nt namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0 .000 secs).`
> I am testing the Matrix-EmailBot, Login on Matrix runs fine, also sending an eMail via the same account ist running fine, just imap bridging to Matrix fails.

Did you check if your selected mailbox is available on your IMAP server? 
By default the mailbox is 'INBOX' you can manually set it with <br>`!setup imap, (host), (username), (password), (INBOX)`

**Comment by JojiiOfficial** [comment]
@mtauz I have commited a new version. This includes 

- listing available mailboxes
- changing current mailbox in a room
- showing the currently selected mailbox

hope this helps

Jojii

**Comment by mtauz** [comment]
It´s running fine, I missed the parameter for INBOX, since I gave the bot a
`!setup imap, (host), (username), (password), false` - the false for ignoreTLS - so the bot took ist as the (INBOX) parameter. 
I think, the bot could answer the given parameters **for veryfying** like this: 
`
Bridge created successfully!
imap, (imap.your.host), (your.username), (*****pw*****), 
No mailboxname specified! Using INBOX
No port specified! Using 993
You should delete the message containing your credentials ;)
`
